---
language: go

go:
  - 1.8.x
  - tip

go_import_path: github.com/mantl/consul-cli

install: 
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
  - glide install
  - make vendor

script: make test
