---
language: go

go:
  - 1.8.x
  - 1.10.x
  - tip

go_import_path: github.com/mantl/consul-cli

install:
  - curl https://releases.hashicorp.com/consul/1.2.3/consul_1.2.3_linux_amd64.zip -o consul.zip
  - unzip consul.zip
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.13.2 && go install && cd -
  - glide install
  - make vendor

script: env PATH="$TRAVIS_BUILD_DIR:$PATH" make test
